apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightspeed-agent.fullname" . }}
  labels:
    {{- include "lightspeed-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    {{- include "lightspeed-agent.agentSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.agent.port }}
      targetPort: {{ .Values.agent.port }}
      protocol: TCP
      name: http
  type: ClusterIP
