{{- if .Values.handler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightspeed-agent.fullname" . }}-gcp-sa-key
  labels:
    {{- include "lightspeed-agent.labels" . | nindent 4 }}
type: Opaque
data:
  sa-key.json: {{ .Values.secrets.gcpServiceAccountKey }}
{{- end }}
